### ISSUE TITLE
cellranger_count not delocalizing outputs

### ISSUE THREAD

**Issue by majorkazer** [klarman-cell-observatory/cumulus#136]
Hello,

I am running the cellranger workflow on data from a NextSeq run where the sample is split across all four lanes. When I specify `Lane` to be `1` on the sample sheet, the pipeline completes as expected. However, when I try `1-4` or `*`, the pipeline seems to have issues outputting the results from `cellranger_count`. The sample folders are not created and populated, so the downstream steps like `collect_summaries` are throwing exceptions because they can't find the files.

Are these files stored anywhere else after delocalization if they aren't moved to the `cellranger_output` folder

Thanks!

**Comment by majorkazer** [comment]
Actually - I think this is a cacheing issue. I had deleted all of the outputs, but it seems like when I tried to resubmit the workflow, it was still using the cache from the successful first attempt with `Lane` set to `1`.

**Comment by yihming** [comment]
In case of the caching issue, instead of deleting your outputs, you can either unselect the "Use call caching" checkbox in the workflow page of `cellranger_workflow` (see below)

<img width="380" alt="Screen Shot 2021-01-06 at 16 45 18" src="https://user-images.githubusercontent.com/2455754/103822838-d532c200-503e-11eb-8a34-c3c119c4197c.png">

or remove the folder directly related to your previous submission (you can open the submission folder by clicking your job from the Job History tab, see below)

<img width="1049" alt="Screen Shot 2021-01-06 at 16 43 45" src="https://user-images.githubusercontent.com/2455754/103822837-d532c200-503e-11eb-8b34-0bc3ff6a9c00.png">
