### ISSUE TITLE
software organization

### ISSUE THREAD

**Issue by slowkow** [klarman-cell-observatory/cumulus#2]
I'd like to ask if I have an accurate mental model of how these 3 software components are related: **altocumulus**, **cumulus**, and **pegasus**.

Here is my current understanding:

- The **altocumulus** Python package allows users to run Workflows registered in Terra Workspaces from the command line (instead of navigating the Terra website). They can run any Terra Workflows, including the pipelines that are defined in the **cumulus** collection.

- The **cumulus** GitHub repo is a collection of WDL files that define Terra Workflows. This collection focuses on pipelines for single-cell data analysis (e.g. bcl2fastq, cellranger, drop-seq, pegasus).

- The **pegasus** Python package provides efficient implementations of key algorithms for single-cell data analysis (e.g. 10x scRNA-seq, TCR-seq, BCR-seq, CITE-seq). Pegasus can be considered an alternative to Scanpy (Python) or Seurat (R).

I am happy there are 3 different names for these components instead of variations on the name "sccloud" (sccloud-util, sccloud, sccloudpy). The new names help me to immediately understand that they are not the same thing and they are not directly dependent on each other.

Here are my questions for you:

1. Is it true that the 3 components can "live alone" without each other?
  
   If I understand correctly, we can use any one of the components without knowing about or using the other two. Is that right?

2. Could I ask if **altocumulus** depends on Terra? In other words, can we use it without Terra if we are using Google Cloud? (I'm new to this.)

3. If the **altocumulus** and **cumulus** are independent, then is it a good idea to use the name "cumulus" in "altocumulus"?

   This naming scheme might suggest to users that "altocumulus" is somehow related to "cumulus", or that it depends on "cumulus", but I am not sure if there is any direct relationship or dependency.

**Comment by bli25broad** [comment]
Hi @slowkow ,

Sorry for the late reply. Please see my replies below:

1. Pegasus is an independent package comparable to SCANPY and Seurat. You do not need to know Cumulus or altocumulus in order to use Pegasus. Cumulus refers to the whole cloud pipeline and it uses Pegasus for its analysis. However, since everything is dockerized, users do not need to understand Pegasus in order to use Cumulus. Altocumulus is a utility tool we have developed to make job submission easier. It depends on Cumulus.

2. Yes, altocumulus depends on Terra. You cannot use it directly on Google Cloud.

3. Unfortunately, altocumulus is part of Cumulus suite and depends on Cumulus.

Hope it helps,
Bo
